#!/bin/bash -l 
#SBATCH -p amd_256 
#SBATCH -N 1 
#SBATCH -n 64 
#SBATCH -J PBEsol-relaxation
 
source /public3/soft/modules/module.sh 
module load mpi/oneAPI/2022.1 
export PATH=/public3/home/a6s000254/software-a6s000254/bin-642:$PATH 
 
if [ ! -f POSCAR-org ]; then 
   cp POSCAR POSCAR-org 
fi 
cp INCAR-relax  INCAR 


mpirun -np  64  vasp_std 

cp  CONTCAR    POSCAR 
 
 
